import Footer from "@/components/HeaderFooter/Footer/Footer";
import Header from "@/components/HeaderFooter/Header/Header";
import "@/styles/globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <html lang="en">
        <body className={inter.className}>
          <div className="wrapper" id="wrapper">
            <Header />
            <main>
              {children}
              <ToastContainer />
            </main>
            <Footer />
          </div>
        </body>
      </html>
    </>
  );
}
