import { Footer, Header, SessionWrapper } from "@/components";
import "@/styles/globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <div className="wrapper" id="wrapper">
            <SessionWrapper>
              <Header />
              <main>
                {children}
                <ToastContainer />
              </main>
              <Footer />
            </SessionWrapper>
          </div>
        </body>
      </html>
    </>
  );
}
